stages:
  - build
  - deploy

build:
  image: python:3.9-alpine
  stage: build
  script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry install
    - poetry run build

deploy:
  image: docker:latest
  stage: deploy
  script:
    - docker build -t my-fastapi-app .
    - docker push my-fastapi-app
    - ssh user@production-server "docker pull my-fastapi-app && docker run -d -p 80:80 my-fastapi-app"
